Repository phpbrew/phpbrew, pull requests merged in 2019-11, with the labels that each got.

#1046 Japanese document, add space for markdown head.
  README.ja.md
Labels: Documentation

#1051 Improved Fish-shell completion
  shell/phpbrew.fish
  src/PhpBrew/Command/AppCommand.php
  src/PhpBrew/Command/AppCommand/GetCommand.php
  src/PhpBrew/Command/AppCommand/ListCommand.php
  src/PhpBrew/Command/ExtensionCommand/ConfigCommand.php
  src/PhpBrew/Command/ExtensionCommand/InstallCommand.php
  src/PhpBrew/Command/ExtensionCommand/ShowCommand.php
  src/PhpBrew/Command/FpmCommand/SetupCommand.php
  src/PhpBrew/Command/FpmCommand/StopCommand.php
  src/PhpBrew/Command/InstallCommand.php
  src/PhpBrew/Downloader/DownloadFactory.php
Labels: Backward Incompatible Change, Fish, Improvement

#1054 Removed a trailing comma from the function call in PHP53Patch.php
  src/PhpBrew/Patches/PHP53Patch.php
Labels: Bug

#1038 Updated corneltek/curlkit to the latest version containing c9s/CurlKit#6
  composer.json
  composer.lock
Labels: Bug, Downloaders

#1055 Improved escaping of command line arguments
  src/PhpBrew/CommandBuilder.php
  src/PhpBrew/Extension/ExtensionInstaller.php
  src/PhpBrew/Tasks/ConfigureTask.php
  tests/PhpBrew/CommandBuilderTest.php
Labels: Improvement

#1057 Clean up the temporary directory used during a package extraction
  src/PhpBrew/Tasks/ExtractTask.php
Labels: Bug

#1058 Fixed the switch-off subcommand in Fish
  shell/bashrc
  shell/phpbrew.fish
Labels: Bash, Bug, Fish
