Repository phpbrew/phpbrew, pull requests merged in 2019-12, with the labels that each got.

#1059 Allow to reference PHP -dev builds without using the php- prefix
  shell/bashrc
  shell/phpbrew.fish
  src/PhpBrew/BuildFinder.php
Labels: Bash, Fish, Improvement

#1062 Use the proper order of arguments when calling implode()
  src/PhpBrew/PatchKit/RegExpPatchRule.php
Labels: Bug, PHP 7.4

#1063 Updated the CLIFRamework dependency constraint
  composer.json
  composer.lock
Labels: Bug

#1065 Updated CurlKit and PEARX dependency constraints to the latest stable versions
  composer.json
  composer.lock
Labels: Improvement

#1066 Fix match() function for PHP56WithOpenSSL11Patch
  src/PhpBrew/Patches/PHP56WithOpenSSL11Patch.php
Labels: Bug, OpenSSL

#1070 Cleaned up the test suite a bit
  phpunit.xml.dist
  tests/PhpBrew/VariantBuilderTest.php
Labels: Improvement, Test Suite

#1071 Enforced PHP version in Composer configuration
  .travis.yml
  composer.json
  composer.lock
Labels: Dependencies, Improvement

#1072 Replaced abandoned satooshi/php-coveralls with php-coveralls/php-coveralls
  .travis.yml
  composer.json
  composer.lock
Labels: Dependencies, Improvement, Test Suite

#1076 Removed unused dependencies
  composer.json
  composer.lock
Labels: Dependencies, Improvement

#1077 Disable travis builds on other branches than master
  .travis.yml
  phpunit.xml.dist
Labels: CI, Improvement, Test Suite

#1078 Fixed VCR issues
  .gitignore
  src/PhpBrew/Testing/VCRAdapter.php
Labels: Improvement, Test Suite

#1079 Speed up slow tests on PHP 5
  .gitignore
  tests/PhpBrew/Command/InstallCommandTest.php
  tests/PhpBrew/Extension/ExtensionInstallerTest.php
  tests/fixtures/vcr_cassettes/Command/KnownCommandTest
  tests/fixtures/vcr_cassettes/Command/UpdateCommandTest
  tests/fixtures/vcr_cassettes/Downloader/DownloaderTest
  tests/fixtures/vcr_cassettes/Extension/ExtensionManagerTest
  tests/fixtures/vcr_cassettes/Extension/ExtensionTest
  tests/fixtures/vcr_cassettes/Extension/KnownCommandTest
  tests/fixtures/vcr_cassettes/KnownCommandTest
  tests/fixtures/vcr_cassettes/UpdateCommandTest
Labels: CI, Improvement, Test Suite

#1080 Removed unused platform-related code and tests
  src/PhpBrew/Platform/Hardware.php
  src/PhpBrew/Platform/Linux.php
  src/PhpBrew/Platform/Linux/CentOS.php
  src/PhpBrew/Platform/Linux/Debian.php
  src/PhpBrew/Platform/Linux/Distribution.php
  src/PhpBrew/Platform/Linux/UnknownDistribution.php
  src/PhpBrew/Platform/Mac.php
  src/PhpBrew/Platform/Platform.php
  src/PhpBrew/Platform/PlatformInfo.php
  src/PhpBrew/Platform/UnixLikeHardware.php
  src/PhpBrew/Platform/UnknownPlatform.php
  tests/PhpBrew/Platform/Linux/CentOSTest.php
  tests/PhpBrew/Platform/Linux/DebianTest.php
  tests/PhpBrew/Platform/Linux/UnknownDistributionTest.php
  tests/PhpBrew/Platform/LinuxTest.php
  tests/PhpBrew/Platform/MacTest.php
  tests/PhpBrew/Platform/PlatformInfoTest.php
  tests/PhpBrew/Platform/UnixLikeHardwareTest.php
  tests/PhpBrew/Platform/UnknownPlatformTest.php
Labels: Improvement

#1081 Removed topics from the application
  Makefile
  phpcs.xml.dist
  phpunit.xml.dist
  src/PhpBrew/Console.php
  src/PhpBrew/Topic/ContributionTopic.php
  src/PhpBrew/Topic/CookbookTopic.php
  src/PhpBrew/Topic/HomeTopic.php
  src/PhpBrew/Topic/MigratingFromHomebrewPhpToPhpbrewTopic.php
  src/PhpBrew/Topic/PHPBrewJATopic.php
  src/PhpBrew/Topic/ReleaseProcessTopic.php
  src/PhpBrew/Topic/RequirementTopic.php
  src/PhpBrew/Topic/SettingUpConfigurationTopic.php
  src/PhpBrew/Topic/TroubleshootingTopic.php
Labels: Documentation, Improvement

#1069 Fix makefile.global for apache2 module name patch
  src/PhpBrew/Patches/Apache2ModuleNamePatch.php
  src/PhpBrew/Tasks/BeforeConfigureTask.php
  tests/PhpBrew/Patches/Apache2ModuleNamePatchTest.php
  tests/expected/php/7.4.0-apxs-patch/build/Makefile.global
  tests/expected/php/7.4.0-apxs-patch/configure
  tests/fixtures/php/7.4.0/build/Makefile.global
  tests/fixtures/php/7.4.0/configure
Labels: Apache2, Improvement, PHP 7.4

#1083 Removed the unsupported mirror option from the download and install subcommands
  completion/bash/_phpbrew
  completion/zsh/_phpbrew
  shell/phpbrew.fish
  src/PhpBrew/Command/DownloadCommand.php
  src/PhpBrew/Command/InstallCommand.php
Labels: BC Break, Improvement

#1084 When doing a self-update, download the file from GitHub releases instead of the repository
  README.cn.md
  README.ja.md
  README.md
  README.pt-br.md
  completion/bash/_phpbrew
  completion/zsh/_phpbrew
  shell/phpbrew.fish
  src/PhpBrew/Command/SelfUpdateCommand.php
Labels: Improvement

#1088 Deprecated the AppStore component
  completion/bash/_phpbrew
  completion/zsh/_phpbrew
  shell/phpbrew.fish
  src/PhpBrew/Command/AppCommand.php
  src/PhpBrew/Command/AppCommand/GetCommand.php
  src/PhpBrew/Command/AppCommand/ListCommand.php
Labels: App Store, Deprecation

#1087 Code cleanup
  .travis.yml
  src/PhpBrew/Build.php
  src/PhpBrew/BuildFinder.php
  src/PhpBrew/BuildSettings/BuildSettings.php
  src/PhpBrew/Command/CtagsCommand.php
  src/PhpBrew/Command/DownloadCommand.php
  src/PhpBrew/Command/ExtensionCommand.php
  src/PhpBrew/Command/ExtensionCommand/InstallCommand.php
  src/PhpBrew/Command/FpmCommand/SetupCommand.php
  src/PhpBrew/Command/InstallCommand.php
  src/PhpBrew/Command/KnownCommand.php
  src/PhpBrew/Config.php
  src/PhpBrew/Distribution/DistributionUrlPolicy.php
  src/PhpBrew/Downloader/CurlCommandDownloader.php
  src/PhpBrew/Downloader/WgetCommandDownloader.php
  src/PhpBrew/Exception/SystemCommandException.php
  src/PhpBrew/Exception/TaskFailureException.php
  src/PhpBrew/Extension/Extension.php
  src/PhpBrew/Extension/ExtensionDownloader.php
  src/PhpBrew/Extension/ExtensionFactory.php
  src/PhpBrew/Extension/ExtensionManager.php
  src/PhpBrew/Extension/M4Parser.php
  src/PhpBrew/Extension/PeclExtension.php
  src/PhpBrew/Extension/Provider/PeclProvider.php
  src/PhpBrew/ExtensionList.php
  src/PhpBrew/Machine.php
  src/PhpBrew/Migrations.php
  src/PhpBrew/PatchKit/DiffPatchRule.php
  src/PhpBrew/PatchKit/RegExpPatchRule.php
  src/PhpBrew/PatchPHP.php
  src/PhpBrew/PatchUtils.php
  src/PhpBrew/Paths.php
  src/PhpBrew/Process.php
  src/PhpBrew/ReleaseList.php
  src/PhpBrew/Tasks/AfterConfigureTask.php
  src/PhpBrew/Tasks/Apxs2CheckTask.php
  src/PhpBrew/Tasks/BaseTask.php
  src/PhpBrew/Tasks/BeforeConfigureTask.php
  src/PhpBrew/Tasks/ConfigureTask.php
  src/PhpBrew/Tasks/DefaultConfigTask.php
  src/PhpBrew/Tasks/RemoveTask.php
  src/PhpBrew/Testing/PatchTestCase.php
  src/PhpBrew/Testing/TemporaryFileFixture.php
  src/PhpBrew/Utils.php
  src/PhpBrew/VariantBuilder.php
  src/PhpBrew/Version.php
  tests/PhpBrew/Command/InstallCommandTest.php
  tests/PhpBrew/Distribution/DistributionUrlPolicyTest.php
  tests/PhpBrew/MachineTest.php
  tests/PhpBrew/PatchUtilsTest.php
  tests/PhpBrew/VersionTest.php
Labels: Improvement

#1089 Removing the development dependency on corneltek/phpunit-testmore
  composer.json
  composer.lock
  tests/PhpBrew/BuildSettings/BuildSettingsTest.php
  tests/PhpBrew/BuildSettings/DefaultBuildSettingsTest.php
  tests/PhpBrew/BuildTest.php
  tests/PhpBrew/ConfigTest.php
  tests/PhpBrew/Tasks/MakeTaskTest.php
Labels: Improvement, Test Suite

#1090 PHPUnit 6
  composer.json
  composer.lock
  tests/PhpBrew/ConfigTest.php
  tests/PhpBrew/Extension/ExtensionManagerTest.php
  tests/bootstrap.php
Labels: Improvement, Test Suite

#1091 PHPUnit 7
  composer.json
  composer.lock
  src/PhpBrew/PatchKit/DiffPatchRule.php
  src/PhpBrew/PatchKit/Patch.php
  tests/PhpBrew/Command/InstallCommandTest.php
  tests/PhpBrew/Command/PathCommandTest.php
  tests/PhpBrew/VariantBuilderTest.php
  tests/bootstrap.php
Labels: Improvement, Patching PHP, Regression, Test Suite

#1092 Removed the development dependency on php-coveralls/php-coveralls
  .travis.yml
  composer.json
  composer.lock
Labels: CI, Dependencies, Improvement

#1093 Made all patches part of the PHPBrew source tree
  src/PhpBrew/PatchKit/DiffPatchRule.php
  src/PhpBrew/Patches/FreeTypePatch.php
  src/PhpBrew/Patches/GistContent.php
  src/PhpBrew/Patches/PHP53Patch.php
  src/PhpBrew/Patches/PHP56WithOpenSSL11Patch.php
  tests/PhpBrew/Patches/FreeTypePatchTest.php
  tests/expected/php/7.3.12-freetype-patch/ext/gd/config.m4
  tests/fixtures/php/7.3.12/ext/gd/config.m4
Labels: Improvement, Patching PHP

#1094 Deprecated the usage of multiple variants in one command line argument
  src/PhpBrew/Command/InstallCommand.php
  src/PhpBrew/VariantParser.php
  tests/PhpBrew/VariantParserTest.php
Labels: Deprecation, Improvement, Test Suite

#1082 Replaced the existing PHAR building implementation with Humbug/Box
  .gitattributes
  .gitignore
  .hhconfig
  CONTRIBUTORS.md
  Doxyfile
  HACKING.md
  Makefile
  assets/php-releases.json
  bin/phpbrew
  box.json.dist
  build.xml
  build/.keep
  flavors/command/Generator.php
  flavors/command/Resource/.gitignore
  flavors/command/Resource/Command.php.twig
  phpdox.xml
  phpmd.xml
  phprelease.ini
  scripts/compile
  scripts/phpbrew-emb.php
  scripts/release
  scripts/update-completion
  scripts/update-testing-fixtures
  sh/Gemfile
  sh/Guardfile
  sh/Rakefile
  sh/bin/installer
  sh/tests/bin/installer_comment_test.sh
  sh/tests/mock/installer_mock.sh
  tests/bootstrap-phar.php
  todo.md
Labels: Improvement

#1095 Fixed code coverage
  src/PhpBrew/Patches/FreeTypePatch.php
  src/PhpBrew/Patches/PHP53Patch.php
  src/PhpBrew/Patches/PHP56WithOpenSSL11Patch.php
Labels: Regression, Test Suite

#1096 Implemented the each subcommand in Fish
  shell/phpbrew.fish
Labels: Fish, Improvement

#1097 Removed the DefaultBuildSettings class
  src/PhpBrew/BuildSettings/DefaultBuildSettings.php
  src/PhpBrew/Command/InstallCommand.php
  tests/PhpBrew/BuildSettings/DefaultBuildSettingsTest.php
Labels: Code Quality, Improvement

#1099 Removed unnecessary top-level dependency on corneltek/class-template
  composer.json
  composer.lock
Labels: Improvement

#1100 Removed deprecated Config::getInstalledPhpVersions()
  src/PhpBrew/BuildFinder.php
  src/PhpBrew/Command/CleanCommand.php
  src/PhpBrew/Command/CtagsCommand.php
  src/PhpBrew/Command/EnvCommand.php
  src/PhpBrew/Command/ListCommand.php
  src/PhpBrew/Command/PurgeCommand.php
  src/PhpBrew/Command/SwitchCommand.php
  src/PhpBrew/Command/UseCommand.php
  src/PhpBrew/Config.php
  tests/PhpBrew/Command/InstallCommandTest.php
Labels: Improvement

#1064 Added `sodium` as variant.
  src/PhpBrew/VariantBuilder.php
Labels: Improvement, Variants

#1098 Implemented the usage of the system PHP interpreter
  bin/phpbrew
  completion/bash/_phpbrew
  completion/zsh/_phpbrew
  shell/bashrc
  shell/phpbrew.fish
  src/PhpBrew/Command/EnvCommand.php
  src/PhpBrew/Command/SystemCommand.php
  src/PhpBrew/Command/SystemOffCommand.php
  src/PhpBrew/Console.php
Labels: Feature, Important, Improvement, RFC, Refactoring

#1101 Fixed duplicate $PHPBREW_PATH in $PATH in Fish
  shell/bashrc
  shell/phpbrew.fish
Labels: Bug, Fish, Improvement

#1105 Fixed __phpbrew_normalize_build in Bash
  shell/bashrc
Labels: Bash, Bug, Regression

#1106 Drop support for PHP 7.1 and older as runtime
  .travis.yml
  bin/phpbrew
  composer.json
  composer.lock
  shell/bashrc
  shell/phpbrew.fish
Labels: BC Break, Improvement

#1107 Added PHP_CodeSniffer as a development dependency
  .prettyci.composer.json
  composer.json
  composer.lock
  src/PhpBrew/BuildFinder.php
  src/PhpBrew/VariantBuilder.php
  tests/PhpBrew/Patches/Apache2ModuleNamePatchTest.php
Labels: Code Quality, Improvement

#1109 Switched from Style-CI to PrettyCI
  .prettyci.composer.json
  README.cn.md
  README.md
  src/PhpBrew/BuildFinder.php
  src/PhpBrew/VariantBuilder.php
  tests/PhpBrew/Patches/Apache2ModuleNamePatchTest.php
Labels: Code Quality, Improvement

#1108 Removed package dependency on the DOMDocument extension
  composer.json
  composer.lock
  src/PhpBrew/Extension/Provider/PeclProvider.php
Labels: Improvement

#1110 Removed the --official flag of the update command
  completion/bash/_phpbrew
  completion/zsh/_phpbrew
  shell/phpbrew.fish
  src/PhpBrew/Command/UpdateCommand.php
Labels: BC Break, Improvement

#1111 Updated the locked PHPUnit version to 7.5
  .travis.yml
  composer.json
  composer.lock
Labels: Improvement, Test Suite

#1112 Fixed shell completion of the remove command
  completion/zsh/_phpbrew
  src/PhpBrew/Command/RemoveCommand.php
Labels: Bug, Regression

#1113 Make sure we update the completion files when needed
  completion/bash/_phpbrew
  tests/PhpBrew/CompletionTest.php
Labels: Improvement, Test Suite

#1114 Improved error handling in the use and switch commands
  shell/bashrc
  shell/phpbrew.fish
Labels: Bash, Bug, Fish

#1115 Updated the PEARX to 1.3.5
  composer.json
  composer.lock
Labels: Improvement

#1085 Add PKG_CONFIG_PATH environment variables to phpbrew build process
  src/PhpBrew/Build.php
  src/PhpBrew/Command/InstallCommand.php
  src/PhpBrew/VariantBuilder.php
Labels: Extension Installer, GD, Improvement, OpenSSL, PHP 7.4, XML

#1118 Add homebrew support for bz2 and iconv
  src/PhpBrew/VariantBuilder.php
Labels: Improvement, Variants

#1119 Update README.md
  README.md
Labels: Documentation, Improvement

#1121 Code cleanup
  .travis.yml
  src/PhpBrew/Build.php
  src/PhpBrew/BuildRegister.php
  src/PhpBrew/Command/InitCommand.php
  src/PhpBrew/Config.php
  src/PhpBrew/Tasks/PrepareDirectoryTask.php
  tests/PhpBrew/BuildRegisterTest.php
  tests/PhpBrew/ConfigTest.php
Labels: Improvement

#1120 Refactored building `./configure` command-line options and environment variables
  README.cn.md
  README.ja.md
  README.md
  README.pt-br.md
  src/PhpBrew/Build.php
  src/PhpBrew/BuildSettings/BuildSettings.php
  src/PhpBrew/Command/InstallCommand.php
  src/PhpBrew/ConfigureParameters.php
  src/PhpBrew/PrefixFinder/UserProvidedPrefix.php
  src/PhpBrew/Tasks/Apxs2CheckTask.php
  src/PhpBrew/Tasks/BeforeConfigureTask.php
  src/PhpBrew/Tasks/ConfigureTask.php
  src/PhpBrew/VariantBuilder.php
  src/PhpBrew/VariantParser.php
  tests/PhpBrew/BuildSettings/BuildSettingsTest.php
  tests/PhpBrew/BuildTest.php
  tests/PhpBrew/ConfigureParametersTest.php
  tests/PhpBrew/Patches/Apache2ModuleNamePatchTest.php
  tests/PhpBrew/Patches/IntlWith64bitPatchTest.php
  tests/PhpBrew/Patches/OpenSSLDSOPatchTest.php
  tests/PhpBrew/VariantBuilderTest.php
  tests/PhpBrew/VariantParserTest.php
Labels: BC Break, Improvement, Refactoring, Variants

#1122 Replaced the GZ PHAR compression algorithm with BZ2
  box.json.dist
Labels: Improvement

#1123 Fix the patch corrupted after inlining
  src/PhpBrew/Patches/PHP56WithOpenSSL11Patch.php
  tests/PhpBrew/Patches/PHP56WithOpenSSL11PatchTest.php
  tests/expected/php/5.6.40-php56-openssl11-patch/ext/openssl/openssl.c
  tests/expected/php/5.6.40-php56-openssl11-patch/ext/openssl/xp_ssl.c
  tests/expected/php/5.6.40-php56-openssl11-patch/ext/phar/util.c
  tests/fixtures/php/5.6.40/ext/openssl/openssl.c
  tests/fixtures/php/5.6.40/ext/openssl/xp_ssl.c
  tests/fixtures/php/5.6.40/ext/phar/util.c
Labels: Bug, OpenSSL, Patching PHP, Regression

#1124 Improved building mbstring on PHP 7.4
  src/PhpBrew/Build.php
  src/PhpBrew/BuildSettings/BuildSettings.php
  src/PhpBrew/VariantBuilder.php
Labels: Improvement, PHP 7.4, Variants

#1125 Rebuilt composer.lock from scratch and updated some dependencies
  composer.json
  composer.lock
Labels: Bug, Dependencies, Improvement

#1126 Removed the AppStore feature
  completion/bash/_phpbrew
  completion/zsh/_phpbrew
  phpunit.xml.dist
  shell/bashrc
  shell/phpbrew.fish
  src/PhpBrew/AppStore.php
  src/PhpBrew/Command/AppCommand.php
  src/PhpBrew/Command/AppCommand/GetCommand.php
  src/PhpBrew/Command/AppCommand/ListCommand.php
  src/PhpBrew/Console.php
  tests/PhpBrew/Command/AppCommandTest.php
Labels: App Store, BC Break

#1129 Downgraged corneltek/getoptionkit to v2.3.0
  composer.json
  composer.lock
Labels: Critical, Dependencies, Regression

#1132 Use internal oniguruma to build mbstring/mbregex in previous PHP version before 7.4.0
  src/PhpBrew/VariantBuilder.php
Labels: Regression, Variants

#1136 Get the ini info from the currently used PHP instead of the PHPBrew interpreter
  shell/bashrc
  shell/phpbrew.fish
  src/PhpBrew/Command/ConfigCommand.php
  src/PhpBrew/Command/ExtensionCommand/ConfigCommand.php
  src/PhpBrew/Command/InfoCommand.php
  src/PhpBrew/Utils.php
Labels: Bash, Fish, Regression, System Interpreter

#1142 Use whence -p instead of which in Zsh
  shell/bashrc
Labels: Bug, Regression, Zsh
