Repository phpbrew/phpbrew, pull requests merged in 2020-10, with the labels that each got.

#1196 Add support for Homebrew prefix for php-ldap
  src/PhpBrew/VariantBuilder.php
Labels: Extension Installer

#1190 PhpStreamDownloader: throw exceptions on failure
  src/PhpBrew/Downloader/PhpStreamDownloader.php
Labels: Downloaders

#1197 Do not compress the PHAR
  box.json.dist
  src/PhpBrew/Patches/PHP53Patch.php
  src/PhpBrew/Tasks/AfterConfigureTask.php
Labels: Improvement, Patching PHP

#1200 Rework the +pgsql variant
  src/PhpBrew/PrefixFinder/ExecutablePrefixFinder.php
  src/PhpBrew/VariantBuilder.php
Labels: Variants, macOS

#1201 Deprecate the info and list-ini commands
  src/PhpBrew/Command/InfoCommand.php
  src/PhpBrew/Command/ListIniCommand.php
Labels: Deprecation

#1202 Improve IMAP support on macOS
  src/PhpBrew/Build.php
  src/PhpBrew/ConfigureParameters.php
  src/PhpBrew/Tasks/ConfigureTask.php
  src/PhpBrew/Utils.php
  src/PhpBrew/VariantBuilder.php
Labels: Variants, macOS
